version: 2.1

orbs:
  slack: circleci/slack@4.9.3

working_directory: &working_directory
  ~/project

defafult_config: &default_config
  docker:
    - image: hashicorp/terraform:1.4.5
  working_directory: *working_directory

repo_cache_key: &repo_cache_key
  v1-repo-{{ .Branch }}-{{ .Revision }}

restore_repo: &restore_repo
  restore_cache:
    key: *repo_cache_key

save_repo: &save_repo
  save_cache:
    key: *repo_cache_key
    paths:
      - *working_directory

set_terraform_env: &set_terraform_env
  run:
    name: set terraform env
    command: |
      mkdir -p ~/.config/gcloud
      echo "[ohr486base-terraform]" > ~/.config/gcloud/credentials

terraform_init: &terraform_init
  run:
    name: terraform init
    command: |
      cd ~/project
      terraform init

jobs:
  terraform_fmt_validate:
    <<: *default_config
    steps:
      - checkout
      - *set_terraform_env
      - *terraform_init
      - run:
          name: terraform fmt validate
          command: |
            cd ~/project
            terraform fmt
            terraform validate
      - *save_repo

  terraform_plan:
    <<: *default_config
    steps:
      - *restore_repo
      - *set_terraform_env
      - run:
          name: install curl
          command: |
            apk --no-cache add curl
      - run:
          name: terraform plan
          command: |
            cd ~/project
            terraform plan
      - slack/notify:
          event: always

  terraform_apply:
    <<: *default_config
    steps:
      - *restore_repo
      - *set_terraform_env
      - run:
          name: install curl
          command: |
            apk --no-cache add curl
      - run:
          name: terraform apply
          command: |
            cd ~/project
            terraform apply --auto-approve
      - slack/notify:
          event: always

workflows:
  deploy:
    jobs:
      - terraform_fmt_validate
      - terraform_plan:
          context: ohr486-circleci-notification
          requires:
            - terraform_fmt_validate
      - terraform_apply:
          context: ohr486-circleci-notification
          filters:
            branches:
              only: main
          requires:
            - terraform_plan
